default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: ''
  database: orb_def_development

test:
  <<: *default
  database: orb_def_engine_test
  #  user: <%#= ENV['DB_USER'] %>
  #  password: <%#= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || '' %>
  password: <%= ENV['DB_PASSWORD'] %>

production:
  <<: *default
  url: <%= ENV['DOKKU_POSTGRES_BLACK_URL'] %>
